perf: DataRetiver performance improved
silahian/VisualHFT pull request #26
Opened 2023-10-16 17:32 UTC by ramateur

2023-10-16 21:58 UTC, silahian requested changes

2023-10-16 21:58 UTC, silahian commented on Helpers/HelperOrderBook.cs
> +using ControlzEx.Standard;
Are we using this reference?

2023-10-17 08:13 UTC, ramateur commented on Helpers/HelperOrderBook.cs
> +using ControlzEx.Standard;
No, we are not. Removed in PR.

2023-10-17 12:21 UTC, merged

2023-10-17 12:22 UTC, silahian commented on Helpers/HelperOrderBook.cs
> +using ControlzEx.Standard;
Thanks for this PR. Looks great!